### PR TITLE
Jr/update board layout

### PR DESCRIPTION
**Pull request by jasonreece**
@mjaret  @cchaseView 

We still need to add in the new Board Member's info.

But the layout is in place when we need it.  I'm attaching a photo of the layout.

screen shot 2015-10-05 at 5 45 26 pm

Because we need to use percentages, the distance between the middle row executives is larger than the other two rows.

I have one other suggestion, we could just go in rows of 4.  The last row would only have three, but that is the normal paradigm for the web.

@mjaret - we DON'T want to merge this in yet.  We'll just keep this pull request open, and merge it when we are ready to make it go live.

### CODE REVIEW

**Comment by mjaret** [comment]
Hi Jason,

Ok, thank you.

I haven’t made changes to the following files - these are also showing up as modified (but they weren’t) and so I “ignore” them when I push.    These came up way back when we were first setting up Github - and - they disappeared then reappeared at some point.   No changes to the style sheets (CSS or SCSS).

	modified:   assets/living-style-guide/accordion.html
	modified:   assets/living-style-guide/base.html
	modified:   assets/living-style-guide/buttons.html
	modified:   assets/living-style-guide/carousels.html
	modified:   assets/living-style-guide/index.html
	modified:   assets/living-style-guide/overlays.html



I did make changes to the company file today and that change is showing in Github and is live.

Changes to Jeff title, Rao
Jeff’s new title is Senior Vice President & Chief Strategy Officer, Rao
needs Dr. Rao Mulpuri instead of Rao Mulpuri.

Thanks,

Michael

On Oct 5, 2015, at 2:52 PM, Jason Reece <notifications@github.com> wrote:

@mjaret <https://github.com/mjaret> @cchaseView <https://github.com/cchaseView>
We still need to add in the new Board Member's info.

But the layout is in place when we need it. I'm attaching a photo of the layout.

 <https://cloud.githubusercontent.com/assets/1322996/10294583/4f1a5bf0-6b89-11e5-95a4-ec9545ec5506.png>
Because we need to use percentages, the distance between the middle row executives is larger than the other two rows.

I have one other suggestion, we could just go in rows of 4. The last row would only have three, but that is the normal paradigm for the web.

@mjaret <https://github.com/mjaret> - we DON'T want to merge this in yet. We'll just keep this pull request open, and merge it when we are ready to make it go live.

You can view, comment on, or merge this pull request online at:

  https://github.com/ViewDynamicGlass/viewglass.com/pull/9 <https://github.com/ViewDynamicGlass/viewglass.com/pull/9>
Commit Summary

not sure why, but the style guide is showing changes
updates layout to 4 / 3 / 4
File Changes

M assets/living-style-guide/accordion.html <https://github.com/ViewDynamicGlass/viewglass.com/pull/9/files#diff-0> (21)
M assets/living-style-guide/base.html <https://github.com/ViewDynamicGlass/viewglass.com/pull/9/files#diff-1> (140)
M assets/living-style-guide/buttons.html <https://github.com/ViewDynamicGlass/viewglass.com/pull/9/files#diff-2> (53)
M assets/living-style-guide/carousels.html <https://github.com/ViewDynamicGlass/viewglass.com/pull/9/files#diff-3> (78)
M assets/living-style-guide/index.html <https://github.com/ViewDynamicGlass/viewglass.com/pull/9/files#diff-4> (140)
M assets/living-style-guide/overlays.html <https://github.com/ViewDynamicGlass/viewglass.com/pull/9/files#diff-5> (77)
M assets/stylesheets/application.min.css <https://github.com/ViewDynamicGlass/viewglass.com/pull/9/files#diff-6> (2)
M assets/stylesheets/modules/_company.scss <https://github.com/ViewDynamicGlass/viewglass.com/pull/9/files#diff-7> (36)
M company/index.html <https://github.com/ViewDynamicGlass/viewglass.com/pull/9/files#diff-8> (161)
Patch Links:

https://github.com/ViewDynamicGlass/viewglass.com/pull/9.patch <https://github.com/ViewDynamicGlass/viewglass.com/pull/9.patch>
https://github.com/ViewDynamicGlass/viewglass.com/pull/9.diff <https://github.com/ViewDynamicGlass/viewglass.com/pull/9.diff>

**Comment by cchaseView** [comment]
Can I see what it looks like in rows of 4 – with the last row only having 3.

This configuration looks unusual.

CC

**Comment by jasonreece** [comment]
This looks much better IMO.  

screen shot 2015-10-05 at 6 38 21 pm

**Comment by jasonreece** [comment]
@cchaseView @mjaret 

This is ready to go.  

@mjaret - Whenever we want to add this to the site, we can just click the merge button here, and then deploy.

screen shot 2015-10-08 at 11 31 51 am

screen shot 2015-10-08 at 11 32 00 am

**Comment by cchaseView** [comment]
Jason, can you center the 3 images on the bottom row?

Sent from my iPhone

On Oct 8, 2015, at 8:35 AM, Jason Reece <notifications@github.com<mailto:notifications@github.com>> wrote:


@cchaseView<https://github.com/cchaseView> @mjaret<https://github.com/mjaret>

This is ready to go.

@mjaret<https://github.com/mjaret> - Whenever we want to add this to the site, we can just click the merge button here, and then deploy.

[screen shot 2015-10-08 at 11 31 51 am]<https://cloud.githubusercontent.com/assets/1322996/10371286/9d62ea42-6db0-11e5-838f-0778efc386d8.png>

[screen shot 2015-10-08 at 11 32 00 am]<https://cloud.githubusercontent.com/assets/1322996/10371288/a152ad9a-6db0-11e5-8e34-7b7bb793eab7.png>

-
Reply to this email directly or view it on GitHub<https://github.com/ViewDynamicGlass/viewglass.com/pull/9#issuecomment-146581127>.


This message and any attachments may contain confidential information of View, Inc. If you are not the intended recipient you are hereby notified that any dissemination, copying or distribution of this message, or files associated with this message, is strictly prohibited. If you have received this message in error, please notify us immediately by replying to the message and delete the message from your computer.

**Comment by jasonreece** [comment]
@cchaseView 

Because we are using a grid system across the site, doing that would make the layout on that row look like the middle row in the top screenshot.  With the spacing wider on the row with 3 items.  They way that it is working now is the normal paradigm for modern web design.

The issue is that we need to use percentages for the widths.

I could strip out the grid system entirely for this section, and attempt to write something custom, but that opens us up to bugs, and layout issues at smaller desktop sizes.

**Comment by cchaseView** [comment]
Ok thanks for the feedback.


On Oct 8, 2015, at 4:16 PM, Jason Reece <notifications@github.com<mailto:notifications@github.com>> wrote:


@cchaseView<https://github.com/cchaseView>

Because we are using a grid system across the site, doing that would make the layout on that row look like the middle row in the top screenshot. With the spacing wider on the row with 3 items. They way that it is working now is the normal paradigm for modern web design.

The issue is that we need to use percentages for the widths.

I could strip out the grid system entirely for this section, and attempt to write something custom, but that opens us up to bugs, and layout issues at smaller desktop sizes.

-
Reply to this email directly or view it on GitHub<https://github.com/ViewDynamicGlass/viewglass.com/pull/9#issuecomment-146713620>.


This message and any attachments may contain confidential information of View, Inc. If you are not the intended recipient you are hereby notified that any dissemination, copying or distribution of this message, or files associated with this message, is strictly prohibited. If you have received this message in error, please notify us immediately by replying to the message and delete the message from your computer.

**Comment by cchaseView** [comment]
Jason,


Sorry for so much back and forth on this, but we are trying to get this exactly right.  One of the reasons we were struggling with the 4 / 3 / 4 layout was because of the image of Harold Huges – which was very large compared to the other image.

We now have a new image of Harold  available (see attached) which should work better.

Can you now retry the 4 / 3 / 4 configuration?  I think it should look quite a bit better.  Please make sure that Tom Leppert continues to be in place.


Thanks,

CC

**Comment by jasonreece** [comment]
@cchaseView - ok, I'll give it a shot, and post a screenshot later this afternoon.

**Comment by cchaseView** [comment]
Thanks!

**Comment by jasonreece** [comment]
@cchaseView - I am not seeing the attachment.  Can you send it?

I need to step out for a few hours, but I'll post a screenshot as soon as I get back.

**Comment by cchaseView** [comment]
Here’s the attachment.  Thanks, Jason.

**Comment by jasonreece** [comment]
@cchaseView - 

screen shot 2015-10-12 at 9 28 26 pm

**Comment by cchaseView** [comment]
Jason, can you also send me a screenshot of the biography for Tom Leppert expanded?

Sent from my iPhone

On Oct 12, 2015, at 6:29 PM, Jason Reece <notifications@github.com<mailto:notifications@github.com>> wrote:


@cchaseView<https://github.com/cchaseView> -

[screen shot 2015-10-12 at 9 28 26 pm]<https://cloud.githubusercontent.com/assets/1322996/10443177/475e8720-7128-11e5-861e-bbbfb5744beb.png>

-
Reply to this email directly or view it on GitHub<https://github.com/ViewDynamicGlass/viewglass.com/pull/9#issuecomment-147569045>.


This message and any attachments may contain confidential information of View, Inc. If you are not the intended recipient you are hereby notified that any dissemination, copying or distribution of this message, or files associated with this message, is strictly prohibited. If you have received this message in error, please notify us immediately by replying to the message and delete the message from your computer.

**Comment by jasonreece** [comment]
@cchaseView 

a152ad9a-6db0-11e5-8e34-7b7bb793eab7

**Pull request merged**
